site_name: My Docs
site_url: https://example.com/
site_dir: ../site/en
theme: 
  name: material
  features: 
    - tabs
nav:
  - Home: index.md

extra:
  alternate:
    - name: English
      link: /mkdocs-playground/en/
      lang: en
    - name: 中文
      link: /mkdocs-playground/zh/
      lang: zh
