site_name: My Docs
site_url: https://example.com/
site_dir: ../site/zh
repo_url: https://github.com/wchaws/mkdocs-playground
theme: 
  name: material
  features: 
    - tabs
nav:
  - 主页: index.md

extra:
  alternate:
    - name: English
      link: /mkdocs-playground/en/
      lang: en
    - name: 中文
      link: /mkdocs-playground/zh/
      lang: zh
