site_name: My Docs
site_url: https://example.com/
theme: 
  name: material
  features: 
    - tabs
nav:
  - 主页: index.md

extra:
  alternate:
    - name: English
      link: ./en/
      lang: en
    - name: 中文
      link: ./zh/
      lang: zh
